repos:
- repo: local
  hooks:
  - id: mypy
    name: MyPy type checking
    entry: python -m mypy .
    language: system
    types: [python]
  - id: black
    name: Black code formatter
    entry: black --check .
    language: system
    types: [python]